from pathlib import Path
import json,shutil,sys
from datetime import datetime,timezone
ROOT=Path.cwd();sys.path.insert(0,str(ROOT))
from experiments.walking.recovery_v49 import digest,manifest,seal
out=ROOT/'outputs/walking-braking-v53';shutil.copy2(ROOT/'scripts/render_compressed_surface_receipt.py',out/'render-source.py');seal(out);manifest(out)
prepare=json.loads((ROOT/'.workspace/v53-final-prepare.json').read_text());doctor=json.loads((ROOT/'.workspace/v53-final-doctor.json').read_text());guard=json.loads((ROOT/'.workspace/v53-final-guard.json').read_text());audit=json.loads((out/'verification.json').read_text())
assert prepare['ready_for_diagnosis'] and not prepare['errors'] and doctor['ready_for_evaluator_setup'] and not guard['processes'] and audit['passed'] and not audit['behavior_accepted']
dest=ROOT/'receipts/walking/20260908-v53-activity-closure';dest.mkdir(exist_ok=False);refs={}
folders=[ROOT/'receipts/walking/20260908-v53-retention-collection',*[ROOT/f'receipts/walking/20260908-v53-braking-{b}' for b in ['flat','repeated','endurance','surfaces']],ROOT/'logs/braking-retention-20260908-v53',ROOT/'experiments/walking/braking-replay-v53',out]
for p in folders:refs[str(p.relative_to(ROOT))]={'verified_files':manifest(p),'manifest_sha256':digest(p/'SHA256SUMS')}
paths=['GOAL.md','TRAINING_ACTUALIZATION.md','docs/workspace/ACTIVE_EXPERIMENT.md','docs/workspace/active-experiment.json','experiments/walking/BRAKING-RESULTS-v53.md','experiments/walking/BRAKING-RETENTION-v53.md','experiment_ops/activity.py','tests/test_experiment_ops.py','duck_workspace/core.py','tests/test_braking_v53.py','.workspace/v53-initial-zero-errors.json','.workspace/v53-original-zero-errors.json','.workspace/audit-braking-v53.py','.workspace/finish-v53.py','.workspace/seal-v53-closure.py','.workspace/v53-audit.log','.workspace/v53-workspace-tests.log','.workspace/v53-focused-tests.log','.workspace/v53-training.log','.workspace/v53-training-guard.json','.workspace/v53-render.log','.workspace/v53-render-guard.json','.workspace/v53-final-prepare.json','.workspace/v53-final-doctor.json','.workspace/v53-final-guard.json','.workspace/v53-collection.log','.workspace/v53-collection-guard.json','.workspace/v53-replay.log']
paths += [str(p.relative_to(ROOT)) for p in (ROOT/'experiments/walking').glob('*freeze-v53.json')]
paths += [f'.workspace/v53-{bank}{suffix}' for bank in ['flat','repeated','endurance','surfaces'] for suffix in ['.log','-guard.json']]
for name in paths:
 p=ROOT/name;target=dest/'retained'/name;target.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(p,target)
result=dict(schema='microduck.activity-closure/v1',completed_at=datetime.now(timezone.utc).isoformat(),activity_complete=True,behavior_accepted=False,candidate_promoted=False,policy_activated=False,held_out_opened=False,new_rl_transitions=0,supervised_updates=8000,all_evaluations_complete=True,collection_states=9,eligible_recovery_branches=9,verified_replay_rows=13055,downhill_sessions_survived=1,downhill_sessions_passed=0,flat_passed=63,flat_total=63,endurance_survived=2,endurance_passed=1,endurance_total=2,surface_passed=5,surface_total=14,verified_controls=94660,exact_prebraking_prefix_controls=36952,workspace_tests_passed=140,focused_tests_passed=2,source_receipts=refs,retained_controller='Original V21 walking / V15 standing with V30 command controller',next_step='Freeze offline joint fit feasibility: separate maximum-error gates for successful-stop retention and downhill recovery, including every stop onset, before further full rollout evaluation.',free_bytes=shutil.disk_usage(ROOT).free,known_compute_processes=guard['processes'],compute_boundary=guard['boundary'],paid_compute_started=False,hardware_operated=False,boundary='Completed local simulation experiment with restored retention and remaining downhill/head/heading failures. Not calibrated physical accuracy or carpet transfer.')
(dest/'result.json').write_text(json.dumps(result,indent=2)+'\n');seal(dest);print('Closure verified:',manifest(dest),'files; free GiB',round(result['free_bytes']/2**30,2))
